Readme build
Concordium/concordium-local-chain pull request #24
Opened 2024-01-11 14:09 UTC by PythonHacker24

## Purpose

Updating the README.md file for the Project and including more descriptive information about the project and Open-Source Contribution as well as the purpose of Concordium L1LC Project

## Changes

More descriptive approach towards explaining the project in a concise manner to provide a clear description for the aim and purpose of the project

## Checklist

- [*] My code follows the style of this project.
- [*] The code compiles without warnings.
- [*] I have performed a self-review of the changes.
- [*] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [*] I accept the above linked CLA.

2024-01-11 16:59 UTC, gachouchani1999 requested changes

2024-01-11 16:59 UTC, gachouchani1999 commented on README.md
> +   git clone https://github.com/your-repository-url/concordium-local-chain.git
FIX URL here

2024-01-11 17:27 UTC, PythonHacker24 commented on README.md
> +   git clone https://github.com/your-repository-url/concordium-local-chain.git
Done, replaced the Link with the Official Concordium GitHub Repository

2024-01-15 10:18 UTC, EmilLa1 requested changes

2024-01-15 10:18 UTC, EmilLa1 commented on install.sh
> +#!/bin/bash
What is the purpose of this script? Surely the user would have cloned the repository already. 

I don't think we should have this script, but instead simply describe the process in the README.md file.

2024-01-15 10:18 UTC, EmilLa1 commented on README.md
> +# Concordium LC1C: Local Chain 1 Click for Concordium Blockchain Development 🌐
I don't understand why this is changed? 

Also, we usually do not use emojis and such in READMEs, let's not start it here.

2024-01-15 10:18 UTC, EmilLa1 commented on DOCUMENTATION.md
> +### Rust Build dependences Issues
Have you tested the tool on all these platforms? 

Let's skip this section and simply spell out the prerequisites in the README. E.g. any required libraries.

2024-01-15 10:18 UTC, EmilLa1 commented on DOCUMENTATION.md
> +### Ram Error Issues
Let's skip this section, and provide the link https://developer.concordium.software/en/mainnet/net/nodes/node-requirements.html#node-requirements some reasonable place in the README.

2024-01-15 11:07 UTC, PythonHacker24 commented on install.sh
> +#!/bin/bash
When the command in the README.md automated install is copied and pasted in the terminal (UNIX-based systems), it will clone the repository, build the Frontend files, Build the Rust binaries for Tauri and exit, providing the user with a file with the whole project setup. 

I am removing it as stated for manual installation.

2024-01-15 11:08 UTC, PythonHacker24 commented on README.md
> +# Concordium LC1C: Local Chain 1 Click for Concordium Blockchain Development 🌐
Sure will remove it as per the requirements

2024-01-15 11:09 UTC, PythonHacker24 commented on DOCUMENTATION.md
> +### Rust Build dependences Issues
Yes, all of them are tested by me on Linux and MacOS, but would fix the DOCUMENTATION.md as per the requirements and update the libraries.

2024-01-15 16:03 UTC, PythonHacker24 commented
Fixed the given issues in the Documentation about the troubleshooting as well as removed the installation script and fixed the README for installation steps.

2024-01-16 08:33 UTC, EmilLa1 approved these changes

2024-01-16 08:33 UTC, merged